### ISSUE TITLE
SSR accordion ID mismatch

### ISSUE THREAD

**Issue by danielwaltz** [kenneth-gray/react-aria-accordion#7]
## Prerequisites

- `react-aria-accordion` version: `1.0.4`
- `react` version: `16.12.0`
- `node` version: `v12.12.0`
- `npm` (or `yarn`) version: `1.21.1`

## What you did

Displayed an accordion with test content.

## What happened

`next` threw a warning.

```
Warning: Prop `id` did not match. Server: "section-23-header" Client: "section-1-header"
```

## Suggested solution

The `accordionId` field value is being persisted on the server and gets incremented every time the page is loaded. Might be better to procedurally produce this ID rather than create and mutate a value in the component instance, or make this a required prop and have the user consuming the library set each section's ID themselves.

**Comment by kenneth-gray** [comment]
Hey Daniel,

I didn't have notifications turned on unfortunately so have only just been made aware of the issues you've raised.

I like the idea of just allowing someone to set the `accordionId` to solve this problem quickly, however it might be better to come up with a relevant reset function for SSR purposes that is called before `renderToString()`. That would make them all reset each time and side step this issue. Thoughts?

**Comment by kenneth-gray** [comment]
I've seen that method used in situations like this.

**Comment by danielwaltz** [comment]
I like options, so both solutions are appealing to me! I think if I had to pick one I would prefer the reset function to sidestep running into the issue altogether.

Ultimately it's your call though! Thanks for looking into my tickets. 😄

**Comment by kenneth-gray** [comment]
I think the reset would be best too. Should have a release for both requests tomorrow.

**Comment by mattboon** [comment]
@danielwaltz did this update work for you?

I can still see your original error with the updated version, I think since the checksum bug relates to `sectionId` incrementing too, given by `<SectionProvider>` inside `<Section>`?
https://github.com/kenneth-gray/react-aria-accordion/blob/master/src/Accordion/Section.tsx#L78

My error:

```
Warning: Prop `id` did not match. Server: "section-79-header" Client: "section-1-header" 
```

@kenneth-gray any chance can you clarify?

**Comment by kenneth-gray** [comment]
Whoops. I didn't really realise, I suspect this is still a problem. Re-opening. I'll try again tonight and improve the test to include all the places that a local variable like this changes. The function name shouldn't change.

**Comment by kenneth-gray** [comment]
@mattboon Would you mind testing this out and confirming this works for you now? I changed the generation of the `sectionId` so that it's not just a global variable any more.

**Comment by mattboon** [comment]
@kenneth-gray thanks for the swift response.

Can confirm the behaviour of `initialiseForSsr()` works as expected and fixes the issue :)

Given @danielwaltz mentioned Next.js in the first post:

With Next.js we do not have access to `renderToString(<App />);` so there are a few options about where to call `initialiseForSsr();`

1.) Add globally to `_app.tsx`

```jsx
import { initialiseForSsr } from 'react-aria-accordion';

class App extends NextApp {
  render () {
    initialiseForSsr()

    return (
      <div>
        ...
      </div>
    )
  }
}
```

2.) Add to pages specifically where `<Accordion>`(s) are used

```jsx
import Accordion, { initialiseForSsr } from 'react-aria-accordion';

const MyPage = () => {
  initialiseForSsr()

  return (
    <div>
      <Accordion>
        ...
      </Accordion>
      <Accordion>
        ...
      </Accordion>
    </div>
  )
}
```

3.) Add to `<MyAccordion>` wrapper and call function there

```jsx
import Accordion, { initialiseForSsr } from 'react-aria-accordion';

const MyAccordion = ({ children }) => {
  initialiseForSsr()

  return (
    <Accordion>
      {() => <div>{children}</div>}
    </Accordion>
  )
}

```

I went with option 3) as at this point I do not have multiple Accordions per page, and wanted to keep accordion logic together in one place.
